version: "3.3"

services:
  turbocar-next: 
    container_name: turbocar-next
    restart: always 
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/turbocar-next
      
    working_dir: /usr/src/turbocar-next
    networks:
      - client-network
      #FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge