version: "3.8"

services:
  turbocar-next: 
    container_name: turbocar-next
    restart: always 
    image: node:20.10.0
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/turbocar-next
      - /usr/src/turbocar-next/node_modules
    working_dir: /usr/src/turbocar-next
    networks:
      - client-network
      #FOR PRODUCTION
    command: bash -c "yarn && yarn run dev"

networks:
  client-network:
    driver: bridge